package com.hohoo.ailab.bounded;

import com.google.gson.GsonBuilder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/** A stored conversation and a request projection have different lifetimes. */
public final class ProjectionScenario {
    private static void require(boolean condition, String message) {
        if (!condition) throw new AssertionError(message);
    }

    public static void main(String[] args) throws Exception {
        Path out = Paths.get(args[0]);
        Files.createDirectory(out);
        Path log = out.resolve("conversation.log");
        String system = "Use only the supplied conversation.";
        String question = "Explain the next step.";
        Map<String, Object> report = new LinkedHashMap<>();
        try (TurnJournal journal = new TurnJournal(log)) {
            journal.commit("one", "My project code is ORCHID-17.", "Recorded.");
            journal.commit("two", "I use Java 8.", "Use a Java 8 compatible client.");
            byte[] before = Files.readAllBytes(log);
            int budget = ContextBudget.request(system,
                journal.history().subList(1, 2), question).length;
            ContextBudget.Selection narrow = ContextBudget.select(
                system, journal.history(), question, budget);
            String payload = new String(narrow.payload, StandardCharsets.UTF_8);
            require(narrow.kept == 1 && !payload.contains("ORCHID-17"), "old fact sent");
            require(Arrays.equals(before, Files.readAllBytes(log)), "projection changed disk");
            report.put("narrow_request_bytes", narrow.payload.length);
            report.put("narrow_kept_turns", narrow.kept);
            report.put("old_fact_in_narrow_request", false);
            report.put("projection_preserved_file_bytes", true);
            // A fixed local reply, not an answer generated by a model.
            journal.commit("three", question, "Local fixture reply.");
            require(journal.history().size() == 3, "commit replaced full history");
        }
        try (TurnJournal recovered = new TurnJournal(log)) {
            String next = "What project code did I provide?";
            int wider = ContextBudget.request(system, recovered.history(), next).length;
            ContextBudget.Selection request = ContextBudget.select(
                system, recovered.history(), next, wider);
            require(request.kept == 3, "restart lost a committed turn");
            require(new String(request.payload, StandardCharsets.UTF_8).contains("ORCHID-17"),
                "widened request lost original fact");
            byte[] beforeRejected = Files.readAllBytes(log);
            int mandatory = ContextBudget.request(system, Collections.emptyList(), next).length;
            boolean rejected = false;
            try {
                ContextBudget.select(system, recovered.history(), next, mandatory - 1);
            } catch (IllegalArgumentException expected) {
                rejected = true;
            }
            require(rejected && Arrays.equals(beforeRejected, Files.readAllBytes(log)),
                "rejection changed disk");
            report.put("reopened_turns", recovered.history().size());
            report.put("wide_request_bytes", request.payload.length);
            report.put("old_fact_in_wide_request", true);
            report.put("rejected_request_preserved_file_bytes", true);
        }
        Files.write(out.resolve("projection.json"), new GsonBuilder().setPrettyPrinting()
            .create().toJson(report).getBytes(StandardCharsets.UTF_8));
        System.out.println(new GsonBuilder().create().toJson(report));
    }
}
